---
# yamllint disable rule:line-length
name: Screencast-Keys CI

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - 'release/v**'
      - 'run-ci/**'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:
    schedule:
      - cron: "0 7 * * *"

jobs:
  build:
    name: Test add-on
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     blender_version:
    #       [
    #         "4.2",
    #       ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Get required packages for Blender
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y blender wget python3 python3-pip zip

      - name: Get required pip packages
        run: pip3 install -r requirements.txt

        # - name: Download Blender
        #   run: bash tools/download_blender.sh ${{ matrix.blender_version }} blender-bin

        # - name: Copy add-on to Blender add-on's directory
        #   run: cp -r src/screencast_keys blender-bin/blender-v${{ matrix.blender_version }}-bin/${{ matrix.blender_version }}/scripts/addons

        # - name: Run add-on unittest
        #   run: blender-bin/blender-v${{ matrix.blender_version }}-bin/blender --factory-startup --background -noaudio --python tests/python/run_tests.py
        #   env:
        #     SK_CONSOLE_MODE: true
